package edu.colorado.cs.ngn.storm.reconfigurable;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

import org.freedesktop.dbus.DBusConnection;
import org.freedesktop.dbus.exceptions.DBusException;

import edu.colorado.cs.ngn.storm.dbus.StormTupleSignal.TupleSignal;

import backtype.storm.task.OutputCollector;
import backtype.storm.task.TopologyContext;
import backtype.storm.topology.OutputFieldsDeclarer;
import backtype.storm.topology.base.BaseRichBolt;
import backtype.storm.tuple.Tuple;

public class DBusSenderBolt extends BaseRichBolt {
	/**
	 * autogenerated ID
	 */
	private static final long serialVersionUID = 1L;
	private ExecutorService execService;
	private DBusConnection connection;
	
	@Override
	public void execute(Tuple arg0) {
		execService.execute(new DBusSenderTask(connection, arg0));
	}

	@Override
	public void prepare(@SuppressWarnings("rawtypes") Map arg0, TopologyContext arg1, OutputCollector arg2) {
		execService = Executors.newCachedThreadPool();
		try {
			connection = DBusConnection.getConnection(DBusConnection.SESSION);
		} catch (DBusException e) {
			System.out.println("Could not get DBus connection");
			e.printStackTrace();
		}
	}

	@Override
	public void declareOutputFields(OutputFieldsDeclarer arg0) {
		// TODO Auto-generated method stub

	}
	
	@Override
	public void cleanup(){
		connection.disconnect();
		execService.shutdown();
		try {
			execService.awaitTermination(DBusReceiverSpout.SHUTDOWN_TIMEOUT, TimeUnit.MILLISECONDS);
		} catch (InterruptedException e) {
			System.out.println("Could not shutdown executor service in "+DBusReceiverSpout.SHUTDOWN_TIMEOUT+" ms in "+this.getClass().getCanonicalName());
		}
	}
	
	private class DBusSenderTask implements Runnable{
		private DBusConnection connection;
		private Tuple tuple;
		
		public DBusSenderTask(DBusConnection connection, Tuple tuple){
			this.connection = connection;
			this.tuple = tuple;
		}

		@Override
		public void run() {
			ByteArrayOutputStream bos = new ByteArrayOutputStream();
			ObjectOutput out = null;
			byte[] objectBytes;
			try{
				
				out = new ObjectOutputStream(bos);
				out.writeObject(tuple.getValues().get(0));
				objectBytes = bos.toByteArray();
				
				TupleSignal tupleSignal = new TupleSignal("/edu/colorado/cs/ngn/storm/reconfigurable/DBusSenderBolt", objectBytes, tuple.getValues().size());
				connection.sendSignal(tupleSignal);
			} catch (IOException e) {
				System.out.println("Could not create ObjectOutputStream or write object to byte array");
				e.printStackTrace();
			} catch (DBusException e) {
				System.out.println("Could not create TupleSignal");
				e.printStackTrace();
			} finally{
				if(out != null){
					try {
						out.close();
					} catch (IOException e) {}
				}
				try {
					bos.close();
				} catch (IOException e) {}
			}
		}
	}

}
